//
//  GossipQueenMainViewController.m
//  Gossip Queen
//
//  Created by Noah Harris on 2/15/13.
//  Copyright (c) 2013 Noah Harris. All rights reserved.
//

#import "GossipQueenMainViewController.h"

@interface GossipQueenMainViewController ()


@end

@implementation GossipQueenMainViewController



- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.
    NSLog(@"Main");
    
    locationManager = [[CLLocationManager alloc] init];
    locationManager.delegate = self;
    locationManager.distanceFilter = kCLDistanceFilterNone; // whenever we move
    locationManager.desiredAccuracy = kCLLocationAccuracyHundredMeters; // 100 m
    [locationManager startUpdatingLocation];
    
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)sendMessage:(id)sender { //stubs are generated by connecting
    NSLog(@"sendMessage");
    
    NSString *text = self.sendField.text;
    self.sendField.text = @"";
    
    PFObject *message = [PFObject objectWithClassName:@"Message"];  //USING class name "Message"
    [message setObject:text forKey:@"text"];
    
    
    
    // Integrating Parse code into our app w00t!
    PFObject *testObject = [PFObject objectWithClassName:@"TestObject"];
    [testObject setObject:@"bar" forKey:@"foo"];
    [testObject save];
    
}

- (IBAction)insertLink:(id)sender {
    NSLog(@"insertLink");
}

- (IBAction)like:(id)sender {
    NSLog(@"like");
}

- (IBAction)dislike:(id)sender {
    NSLog(@"dislike");
}

- (IBAction)save:(id)sender {
    NSLog(@"save");
}

#pragma mark - location manager delegate

- (void)locationManager:(CLLocationManager *)manager
    didUpdateToLocation:(CLLocation *)newLocation
           fromLocation:(CLLocation *)oldLocation
{
    latitude = newLocation.coordinate.latitude;
    longitude = newLocation.coordinate.longitude;
    NSLog(@"New latitude: %f", latitude);
    NSLog(@"New longitude: %f", longitude);
        //TODO
}



@end
